// Command apidocs writes directly readable Markdown from the authored API schemas.
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

func main() {
	input := flag.String("input", "api-docs.yml", "authored API schema")
	out := flag.String("out", "docs/docs/reference", "Markdown output directory")
	flag.Parse()
	if err := generate(*input, *out); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func read(filename string) (map[string]any, error) {
	b, err := os.ReadFile(filename)
	if err != nil {
		return nil, err
	}
	var doc map[string]any
	err = yaml.Unmarshal(b, &doc)
	return doc, err
}

func keys(m map[string]any) []string {
	result := make([]string, 0, len(m))
	for k := range m {
		result = append(result, k)
	}
	sort.Strings(result)
	return result
}

func lookup(doc map[string]any, pointer string) (any, error) {
	var current any = doc
	for _, part := range strings.Split(strings.TrimPrefix(pointer, "#/"), "/") {
		object, ok := current.(map[string]any)
		if !ok {
			return nil, fmt.Errorf("invalid schema reference %s", pointer)
		}
		part = strings.ReplaceAll(strings.ReplaceAll(part, "~1", "/"), "~0", "~")
		current, ok = object[part]
		if !ok {
			return nil, fmt.Errorf("missing schema reference %s", pointer)
		}
	}
	return current, nil
}

func expand(value any, companion map[string]any, depth int) (any, error) {
	if depth > 100 {
		return nil, fmt.Errorf("API schema nesting or reference cycle exceeds 100 levels")
	}
	switch v := value.(type) {
	case map[any]any:
		// YAML response codes can be numeric keys. Normalize them before
		// traversing so their response schemas receive the same expansion.
		normalized := make(map[string]any, len(v))
		for key, child := range v {
			name := fmt.Sprint(key)
			if _, exists := normalized[name]; exists {
				return nil, fmt.Errorf("ambiguous API mapping key %s", name)
			}
			normalized[name] = child
		}
		return expand(normalized, companion, depth+1)
	case map[string]any:
		if ref, ok := v["$ref"].(string); ok && strings.HasPrefix(ref, "./api-docs-ex.yml#/") {
			target, err := lookup(companion, strings.TrimPrefix(ref, "./api-docs-ex.yml"))
			if err != nil {
				return nil, err
			}
			return expand(target, companion, depth+1)
		}
		result := map[string]any{}
		for k, child := range v {
			expanded, err := expand(child, companion, depth+1)
			if err != nil {
				return nil, err
			}
			if k == "$ref" {
				if ref, ok := expanded.(string); ok {
					expanded = strings.TrimPrefix(ref, "./api-docs.yml")
				}
			}
			result[k] = expanded
		}
		return result, nil
	case []any:
		result := make([]any, len(v))
		for i, child := range v {
			item, err := expand(child, companion, depth+1)
			if err != nil {
				return nil, err
			}
			result[i] = item
		}
		return result, nil
	default:
		return value, nil
	}
}

func validateReferences(value any, document map[string]any) error {
	switch node := value.(type) {
	case map[string]any:
		if ref, ok := node["$ref"].(string); ok {
			if !strings.HasPrefix(ref, "#/") {
				return fmt.Errorf("unresolved API reference %s", ref)
			}
			if _, err := lookup(document, ref); err != nil {
				return err
			}
		}
		for _, child := range node {
			if err := validateReferences(child, document); err != nil {
				return err
			}
		}
	case []any:
		for _, child := range node {
			if err := validateReferences(child, document); err != nil {
				return err
			}
		}
	}
	return nil
}

func schema(b *strings.Builder, v any) error {
	data, err := yaml.Marshal(v)
	if err != nil {
		return err
	}
	// Examples inherited from upstream use the reserved example domain in the manual.
	text := strings.ReplaceAll(string(data), "semaphoreui.com", "example.org")
	fmt.Fprintf(b, "```yaml\n%s```\n\n", text)
	return nil
}

func generate(input, out string) error {
	root, err := read(input)
	if err != nil {
		return err
	}
	companion, err := read(filepath.Join(filepath.Dir(input), "api-docs-ex.yml"))
	if err != nil {
		return err
	}
	expanded, err := expand(root, companion, 0)
	if err != nil {
		return err
	}
	root = expanded.(map[string]any)
	if err := validateReferences(root, root); err != nil {
		return err
	}
	paths, ok := root["paths"].(map[string]any)
	if !ok {
		return fmt.Errorf("missing API paths")
	}
	definitions, ok := root["definitions"].(map[string]any)
	if !ok {
		return fmt.Errorf("missing API definitions")
	}
	var endpoints, models strings.Builder
	endpoints.WriteString("<!-- Generated by tools/apidocs; run task docs:gen in the product repository. -->\n\n# API endpoint reference\n\nRead this file directly; no Swagger UI or site build is required.\nSee [API authentication and examples](api.md) and [all data models](api-models.md).\nThe YAML blocks preserve the complete authored operation contract, including nested request schemas, defaults, enums and response codes.\nReferences beginning with `#/definitions/` name entries in the data-model reference.\nReferences beginning with `#/parameters/` or `#/responses/` name reusable entries in the shared contract below.\nThese schemas document the checked-in API contract; consult feature guides for lifecycle and authorization requirements.\n\n## Shared contract\n\n")
	shared := map[string]any{}
	for _, key := range []string{"basePath", "consumes", "produces", "security", "securityDefinitions", "parameters", "responses"} {
		if v, exists := root[key]; exists {
			shared[key] = v
		}
	}
	if err := schema(&endpoints, shared); err != nil {
		return err
	}
	endpoints.WriteString("## Endpoints\n\n")
	methods := []string{"get", "post", "put", "patch", "delete", "head", "options"}
	count := 0
	for i, path := range keys(paths) {
		fmt.Fprintf(&endpoints, "- [`%s%s`](#endpoint-%d)\n", root["basePath"], path, i+1)
	}
	endpoints.WriteString("\n")
	for i, path := range keys(paths) {
		item, ok := paths[path].(map[string]any)
		if !ok {
			return fmt.Errorf("invalid path %s", path)
		}
		fmt.Fprintf(&endpoints, "<a id=\"endpoint-%d\"></a>\n\n## `%s%s`\n\n", i+1, root["basePath"], path)
		if params, exists := item["parameters"]; exists {
			endpoints.WriteString("Parameters shared by all methods at this path:\n\n")
			if err := schema(&endpoints, params); err != nil {
				return err
			}
		}
		for _, method := range methods {
			operation, exists := item[method]
			if !exists {
				continue
			}
			count++
			fmt.Fprintf(&endpoints, "### %s\n\n", strings.ToUpper(method))
			if err := schema(&endpoints, operation); err != nil {
				return err
			}
		}
	}
	models.WriteString("<!-- Generated by tools/apidocs; run task docs:gen in the product repository. -->\n\n# API data models\n\n[Endpoint reference](api-endpoints.md) · [API guide](api.md)\n\nRequired fields, types, enums, defaults and examples are preserved below as YAML schemas inside Markdown.\nA `#/definitions/Name` reference identifies the model named `Name` in this file.\n\n## Contents\n\n")
	for i, name := range keys(definitions) {
		fmt.Fprintf(&models, "- [%s](#model-%d)\n", name, i+1)
	}
	models.WriteString("\n")
	for i, name := range keys(definitions) {
		fmt.Fprintf(&models, "<a id=\"model-%d\"></a>\n\n## %s\n\n", i+1, name)
		if err := schema(&models, definitions[name]); err != nil {
			return err
		}
	}
	if err := os.MkdirAll(out, 0755); err != nil {
		return err
	}
	for name, text := range map[string]string{"api-endpoints.md": endpoints.String(), "api-models.md": models.String()} {
		if err := os.WriteFile(filepath.Join(out, name), []byte(strings.TrimRight(text, "\n")+"\n"), 0644); err != nil {
			return err
		}
	}
	fmt.Printf("apidocs: wrote %d operations and %d models to %s\n", count, len(definitions), out)
	return nil
}
