package sql

import (
	"bytes"
	"fmt"
	"github.com/go-gorp/gorp/v3"
	"github.com/semaphoreui/semaphore/db"
	"github.com/semaphoreui/semaphore/pkg/tz"
	"github.com/semaphoreui/semaphore/util"
	log "github.com/sirupsen/logrus"
	"path"
	"regexp"
	"strings"
	"text/template"
)

var (
	autoIncrementRE  = regexp.MustCompile(`(?i)\bautoincrement\b`)
	serialRE         = regexp.MustCompile(`(?i)\binteger primary key autoincrement\b`)
	dateTimeTypeRE   = regexp.MustCompile(`(?i)\bdatetime\b`)
	tinyintRE        = regexp.MustCompile(`(?i)\btinyint\b`)
	longtextRE       = regexp.MustCompile(`(?i)\blongtext\b`)
	ifExistsRE       = regexp.MustCompile(`(?i)\bif exists\b`)
	changeRE         = regexp.MustCompile(`^alter table \x60(\w+)\x60 change \x60(\w+)\x60 \x60(\w+)\x60 ([\w\(\)]+)( autoincrement)?( not null)?$`)
	dropForeignKeyRE = regexp.MustCompile(`(?i)\bdrop foreign key\b`)
)

const (
	upstreamMigrationTable = "migrations"
	exMigrationTable       = "ex_migrations"
)

// dropMysqlForeignKey drops the foreign key constraint defined on the given
// table column for MySQL/MariaDB. The constraint name is auto-generated by the
// engine and differs across versions (MariaDB 12.1 changed the scheme from
// `<table>_ibfk_<N>` to a different naming), so it must be resolved from
// information_schema rather than hardcoded. Callers must invoke this only for
// the MySQL dialect; it is a no-op when the column has no foreign key.
func dropMysqlForeignKey(tx *gorp.Transaction, table string, column string) error {
	fkName, err := tx.SelectStr(
		`SELECT CONSTRAINT_NAME FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
		 WHERE TABLE_SCHEMA = DATABASE()
		   AND TABLE_NAME = ?
		   AND COLUMN_NAME = ?
		   AND REFERENCED_TABLE_NAME IS NOT NULL
		 LIMIT 1`, table, column)
	if err != nil || fkName == "" {
		return err
	}
	_, err = tx.Exec(fmt.Sprintf("alter table `%s` drop foreign key `%s`", table, fkName))
	return err
}

// getVersionPath is the humanoid version with the file format appended
func getVersionPath(version db.Migration) string {
	if identity, ok := exMigrationIdentity(version.Version); ok {
		return "ex/v" + identity + ".sql"
	}
	return version.HumanoidVersion() + ".sql"
}

// getVersionErrPath is the humanoid version with '.err' and file format appended
func getVersionErrPath(version db.Migration) string {
	if identity, ok := exMigrationIdentity(version.Version); ok {
		return "ex/v" + identity + ".err.sql"
	}
	return version.HumanoidVersion() + ".err.sql"
}

// getVersionSQL takes a path to an SQL file and returns it from embed.FS
// a slice of strings separated by newlines
func getVersionSQL(dialect string, name string, ignoreErrors bool) (queries []string) {
	queries, err := loadVersionSQL(dialect, name)
	if err == nil {
		return queries
	}
	if !ignoreErrors {
		panic(err)
	}
	log.WithError(err).Warnf("migration %s not found", name)
	return nil
}

func loadVersionSQL(dialect string, name string) (queries []string, err error) {
	var (
		asset []byte
	)
	if strings.HasPrefix(name, "ex/") {
		if !validEXMigrationAsset(name) {
			return nil, fmt.Errorf("invalid EX migration asset %q", name)
		}
		asset, err = exDbAssets.ReadFile(path.Join("migrations_ex", strings.TrimPrefix(name, "ex/")))
	} else {
		asset, err = dbAssets.ReadFile(path.Join("migrations", name))
	}
	if err != nil {
		return nil, fmt.Errorf("read migration asset %s: %w", name, err)
	}

	processedSql, err := preprocessSqlDialect(dialect, string(asset))
	if err != nil {
		return nil, fmt.Errorf("preprocess migration asset %s: %w", name, err)
	}

	queries = strings.Split(strings.ReplaceAll(processedSql, ";\r\n", ";\n"), ";\n")
	for i := range queries {
		queries[i] = strings.Trim(queries[i], "\r\n\t ")
	}
	return queries, nil
}

// migrationHistory selects the SQL source and durable history table from an
// explicitly namespaced EX identity. Upstream IDs remain unchanged so their
// established registry and history stay byte-for-byte compatible.
func migrationHistory(version db.Migration) (table string, err error) {
	if strings.Contains(version.Version, "-ex") {
		if _, ok := exMigrationIdentity(version.Version); !ok {
			return "", fmt.Errorf("invalid EX migration version %q", version.Version)
		}
		return exMigrationTable, nil
	}
	return upstreamMigrationTable, nil
}

func exMigrationIdentity(version string) (string, bool) {
	if !strings.Contains(version, "-ex") {
		return "", false
	}
	if _, err := (db.Migration{Version: version}).ParseVersion(); err != nil {
		return "", false
	}
	return version, true
}

func validEXMigrationAsset(name string) bool {
	if !strings.HasPrefix(name, "ex/v") || !strings.HasSuffix(name, ".sql") {
		return false
	}
	identity := strings.TrimPrefix(name, "ex/v")
	identity = strings.TrimSuffix(identity, ".sql")
	identity = strings.TrimSuffix(identity, ".err")
	_, ok := exMigrationIdentity(identity)
	return ok
}

func (d *SqlDb) migrationHistoryInitialized(table string) (bool, error) {
	var query string
	switch d.GetDialect() {
	case util.DbDriverSQLite:
		query = "select count(1) from sqlite_master where type='table' and name=?"
	case util.DbDriverMySQL:
		query = "select count(1) from information_schema.tables where table_schema=database() and table_name=?"
	case util.DbDriverPostgres:
		query = "select count(1) from information_schema.tables where table_schema=current_schema() and table_type='BASE TABLE' and table_name=?"
	default:
		return false, fmt.Errorf("unsupported migration history dialect %q", d.GetDialect())
	}
	count, err := d.Sql().SelectInt(d.PrepareQuery(query), table)
	if err != nil {
		return false, fmt.Errorf("inspect %s history: %w", table, err)
	}
	return count > 0, nil
}

func (d *SqlDb) ensureMigrationHistory(table string) error {
	initialized, err := d.migrationHistoryInitialized(table)
	if err != nil {
		return err
	}
	if initialized {
		return nil
	}

	query := initialSQL
	if table == exMigrationTable {
		query = exMigrationHistorySQL
	}
	if _, err = d.exec(d.prepareMigration(query)); err != nil {
		return fmt.Errorf("create %s history: %w", table, err)
	}
	return nil
}

// ValidateMigrationPlan loads every selected migration before the caller
// changes schema state. Undo validation intentionally ignores entries that are
// not recorded in their owning history table.
func (d *SqlDb) ValidateMigrationPlan(plan []db.Migration, undo bool) error {
	for _, migration := range plan {
		if _, err := migrationHistory(migration); err != nil {
			return err
		}
		if undo {
			applied, err := d.IsMigrationApplied(migration)
			if err != nil {
				return err
			}
			if !applied {
				continue
			}
			if _, err = loadVersionSQL(d.GetDialect(), getVersionErrPath(migration)); err != nil {
				return fmt.Errorf("validate rollback migration %s: %w", migration.Version, err)
			}
			continue
		}
		if _, err := loadVersionSQL(d.GetDialect(), getVersionPath(migration)); err != nil {
			return fmt.Errorf("validate migration %s: %w", migration.Version, err)
		}
	}
	return nil
}

func getDialectConfig(dialect string) any {
	type Config struct {
		Sqlite     bool
		Mysql      bool
		Postgresql bool
	}

	conf := Config{}

	switch dialect {
	case util.DbDriverSQLite:
		conf.Sqlite = true
	case "mysql":
		conf.Mysql = true
	case "postgres":
		conf.Postgresql = true
	}

	return conf
}

func preprocessSqlDialect(dialect string, sql string) (string, error) {

	tmpl, err := template.New("sql").Parse(sql)
	if err != nil {
		return "", err
	}

	var buf bytes.Buffer
	err = tmpl.Execute(&buf, getDialectConfig(dialect))
	if err != nil {
		panic(err)
	}
	return buf.String(), nil
}

// prepareMigration converts migration SQLite-query to current dialect.
// Supported MySQL and Postgres dialects.
func (d *SqlDb) prepareMigration(query string) string {
	switch d.Sql().Dialect.(type) {
	case gorp.MySQLDialect:
		query = autoIncrementRE.ReplaceAllString(query, "auto_increment")
		query = ifExistsRE.ReplaceAllString(query, "")
	case gorp.PostgresDialect:
		m := changeRE.FindStringSubmatch(query)
		if m != nil {
			tableName := m[1]
			oldColumnName := m[2]
			newColumnName := m[3]
			columnType := m[4]
			//autoincrement := m[5] != ""
			columnNotNull := m[6] != ""

			var queries []string
			queries = append(queries,
				"alter table `"+tableName+"` alter column `"+oldColumnName+"` type "+columnType)

			if columnNotNull {
				queries = append(queries,
					"alter table `"+tableName+"` alter column `"+oldColumnName+"` set not null")
			} else {
				queries = append(queries,
					"alter table `"+tableName+"` alter column `"+oldColumnName+"` drop not null")
			}

			if oldColumnName != newColumnName {
				queries = append(queries,
					"alter table `"+tableName+"` rename column `"+oldColumnName+"` to `"+newColumnName+"`")
			}

			query = strings.Join(queries, "; ")
		}

		query = dateTimeTypeRE.ReplaceAllString(query, "timestamp")
		query = tinyintRE.ReplaceAllString(query, "smallint")
		query = longtextRE.ReplaceAllString(query, "text")
		query = serialRE.ReplaceAllString(query, "serial primary key")
		query = dropForeignKeyRE.ReplaceAllString(query, "drop constraint")
		query = identifierQuoteRE.ReplaceAllString(query, "\"")
	}
	return query
}

// IsMigrationApplied queries the database to see if a migration table with this version id exists already
func (d *SqlDb) IsMigrationApplied(migration db.Migration) (bool, error) {
	table, err := migrationHistory(migration)
	if err != nil {
		return false, err
	}
	initialized, err := d.migrationHistoryInitialized(table)

	if err != nil {
		return false, err
	}

	if !initialized {
		return false, nil
	}

	exists, err := d.Sql().SelectInt(
		d.PrepareQuery("select count(1) as ex from "+table+" where version = ?"),
		migration.Version)

	if err != nil {
		return false, err
	}

	return exists > 0, nil
}

// ApplyMigration runs executes a database migration
func (d *SqlDb) ApplyMigration(migration db.Migration) error {
	table, err := migrationHistory(migration)
	if err != nil {
		return err
	}
	queries, err := loadVersionSQL(d.GetDialect(), getVersionPath(migration))
	if err != nil {
		return fmt.Errorf("validate migration %s: %w", migration.Version, err)
	}
	if err = d.ensureMigrationHistory(table); err != nil {
		return err
	}

	// Rebuilding a table that other tables reference by foreign key must run
	// with foreign_keys=OFF: with FK enforcement enabled, renaming rewrites
	// child FK definitions and dropping cascade-deletes child rows. The pragma
	// is a no-op inside a transaction, so toggle it on the connection itself
	// (the pool is limited to a single connection for SQLite).
	if sqliteNeedsFkOff(d.GetDialect(), migration.Version) {
		if _, err = d.exec("PRAGMA foreign_keys = OFF"); err != nil {
			return err
		}
		defer func() {
			if _, fkErr := d.exec("PRAGMA foreign_keys = ON"); fkErr != nil {
				log.WithFields(log.Fields{
					"context": "migration",
					"version": migration.Version,
				}).WithError(fkErr).Fatal("failed to re-enable foreign_keys pragma after migration")
			}
		}()
	}

	tx, err := d.Sql().Begin()
	if err != nil {
		return err
	}

	switch migration.Version {
	case "2.7.8":
		err = migration_2_7_8{db: d}.PreApply(tx)
	case "2.10.24":
		err = migration_2_10_24{db: d}.PreApply(tx)
	case "2.16.8":
		err = migration_2_16_8{db: d}.PreApply(tx)
	case "2.18.4":
		err = migration_2_18_4{db: d}.PreApply(tx)
	case "2.20.4":
		err = migration_2_20_4{db: d}.PreApply(tx)
	case "2.20.2-ex1.1":
		err = exMigration65{db: d}.PreApply(tx)
	}

	if err != nil {
		handleRollbackError(tx.Rollback())
		return err
	}

	for i, query := range queries {
		fmt.Printf("\r [%d/%d]", i+1, len(query))

		if len(query) == 0 {
			continue
		}

		q := d.prepareMigration(query)
		if q == "" {
			continue
		}

		_, err = tx.Exec(q)
		if err != nil {
			handleRollbackError(tx.Rollback())
			return fmt.Errorf("apply migration %s: %w", migration.Version, err)
		}
	}

	switch migration.Version {
	case "2.8.26":
		err = migration_2_8_26{db: d}.PostApply(tx)
	case "2.8.42":
		err = migration_2_8_42{db: d}.PostApply(tx)
	case "2.19.11":
		err = migration_2_19_11{db: d}.PostApply(tx)
	}

	if err != nil {
		handleRollbackError(tx.Rollback())
		return err
	}

	_, err = tx.Exec(d.PrepareQuery("insert into "+table+"(version, upgraded_date) values (?, ?)"), migration.Version, tz.Now())
	if err != nil {
		handleRollbackError(tx.Rollback())
		return err
	}

	fmt.Println()

	return tx.Commit()
}

// sqliteNeedsFkOff reports whether the migration rebuilds SQLite tables that
// are referenced by other tables' foreign keys and therefore must be applied
// (and rolled back) with FK enforcement disabled on the connection.
func sqliteNeedsFkOff(dialect string, version string) bool {
	return dialect == util.DbDriverSQLite && version == "2.19.14"
}

// TryRollbackMigration attempts to rollback the database to an earlier version if a rollback exists.
func (d *SqlDb) TryRollbackMigration(version db.Migration) (err error) {
	table, err := migrationHistory(version)
	if err != nil {
		return err
	}
	applied, err := d.IsMigrationApplied(version)
	if err != nil {
		return err
	}
	if !applied {
		return nil
	}
	queries, err := loadVersionSQL(d.GetDialect(), getVersionErrPath(version))
	if err != nil {
		return fmt.Errorf("validate rollback migration %s: %w", version.Version, err)
	}

	if sqliteNeedsFkOff(d.GetDialect(), version.Version) {
		if _, err = d.exec("PRAGMA foreign_keys = OFF"); err != nil {
			log.WithFields(log.Fields{
				"context": "migration",
				"version": version.Version,
			}).WithError(err).Fatal("failed to disable foreign_keys pragma before migration")
			return err
		}
		defer func() {
			if _, fkErr := d.exec("PRAGMA foreign_keys = ON"); fkErr != nil {
				log.WithFields(log.Fields{
					"context": "migration",
					"version": version.Version,
				}).WithError(fkErr).Fatal("failed to re-enable foreign_keys pragma after rollback")
			}
		}()
	}

	tx, err := d.Sql().Begin()
	if err != nil {
		return err
	}

	defer func() {
		if err == nil {
			err = tx.Commit()
			if err != nil {
				log.WithError(err).WithFields(log.Fields{
					"context": "migration",
					"version": version.Version,
				}).Error("failed to commit undo migration transaction")
			}
		} else {
			_ = tx.Rollback()
			log.Error(err)
		}
	}()

	switch version.Version {
	case "2.16.8":
		err = migration_2_16_8{db: d}.PreRollback(tx)
	case "2.20.4":
		err = migration_2_20_4{db: d}.PreRollback(tx)
	case "2.20.1-ex1.29":
		if applied {
			err = d.preflightMigration22030Rollback(tx)
		}
	case "2.20.2-ex1.1":
		err = exMigration65{db: d}.PreRollback(tx)
	}

	if err != nil {
		return err
	}

	for _, query := range queries {
		fmt.Printf(" [ROLLBACK] > %v\n", query)
		q := d.prepareMigration(query)
		if q == "" {
			continue
		}
		if _, err = d.execTx(tx, q); err != nil {
			fmt.Println(" [ROLLBACK] - Stopping")
			return err
		}
	}

	_, err = d.execTx(tx, "delete from "+table+" where version=?", version.Version)
	return err
}
